name: Prueba Yo
on: push
env:
  GLOBAL_VARIABLE: ValorGlobal
jobs:
  testing:
    name: testeo del aplicativo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Descarga del repositorio
    - name: Acciones a realizar dentro del repositorio descargado
      id: pepe
      run: |
        ls
        pwd
    - name: Lectura de variables
      run: |
        echo " ${{ secrets.TEST_SECRETO }}  "
        echo " ${{ env.GLOBAL_VARIABLE }}  "
