name: Prueba Yo
on: push
jobs:
  testing:
    name: testeo del aplicativo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: Descarga del repositorio
    - name: Acciones a realizar dentro del repositorio descargado
      run: |
        ls
        pwd
    - name: Lectura de variables
      run: |
        echo " ${{ secrets.TEST_SECRETO }}    
